### PR TITLE
Support for Allegro CL 10 expression

### PR DESCRIPTION
**Pull request by binghe**
Hi, dear SWCLOS author,

This is a huge patch to support Allegro CL 10 expression (ANSI mode), while my final goal is to port your package to other CL platforms.  In this patch, I've done at least the following things:
1. Changed all ASDF definition files to support latest ASDF 3.
2. Symbols from xsd:, rdf:, rdfs: and owl: packages are all changed to |-quoted symbols, to support ANSI mode.
3. Use PURI instead of NET.URI (and easily switchable in RDF/packages.cl)
4. Minor clean up and several large files broken down (to support other CL platforms in the future)

(If switching back to NET.URI, Allegro CL 9  modern and ANSI modes are all still supported. I still need to figure out why PURL can't work in ACL9)

P. S. This work is in scope of my exam project for "Artificial Intelligence: Knowledge Representation" course in University of Bologna (Italy), my final goal is to port SWCLOS to other CL platforms (SBCL, LispWorks, Clozure CL, ECL, etc) thus contribute another Semantic Web solution for CL community.

Comments (and help) on code changes are mostly welcome!

Best Regards,

Chun Tian (binghe)
University of Bologna (Italy)

### CODE REVIEW

**Comment by SeijiKoide** [comment]
Dear Chun Tian



Thank you for your interest and contribution to SWCLOS, and I apology that
this reply mail is too late.

Just now, I am attending ISWC2016 that is held at Kobe, Japan.

I will check your program code, honestly and sincerely, but it will take a
couple of weeks.



I ask your favor of your patience.



I am programming swclos2, which is aiming to reflect RDF1.1 and OWL 2, and
"newclassic", which is based on RDF and OWL but much more aiming to apply
SW to application like AI.



However, I know I must debug the current SWCLOS and update it for the
current situation. So, I appreciate your big efforts.

I will respond you after skimming your  work.

Thank you again for your contribution to SWCLOS.



Sincerely

Seiji Koide

2016-10-16 1:05 GMT+09:00 Chun Tian <notifications@github.com>:

**Comment by binghe** [comment]
Hi Seiji Koide,

Thank you, and please take your time. I'll keep working on next stage.  

For swclos2, is it still for Allegro CL only, or it can also run in some other CL platforms?

Regards,

Chun Tian

**Comment by binghe** [comment]
I think it's better to keep your original code base as a reference point. Let's not merge this pull request.

**Comment by SeijiKoide** [comment]
Hi, Chun

> (If switching back to NET.URI, Allegro CL 9 modern and ANSI modes are all
still supported. I still need to figure out why PURL can't work in ACL9)

I dont understand what PURL is. Could you teach me it, with the line which
include "PURL". I might be typo.
I am now in Singapore for JIST2016. So, when I return back to Japan. I will
check SWCLOS and your comment in detail.

> Symbols from xsd:, rdf:, rdfs: and owl: packages are all changed to
|-quoted symbols, to support ANSI mode.

You can use preserving mode of characters, if you like. If you dont know
what it is. Please check
http://www.lispworks.com/documentation/HyperSpec/Body/f_rdtabl.htm#readtable-case
.
However, even though you set up case-sencitive-mode, you can't change the
Common Lisp functions that are already defined case-mode :upcase. So, it is
not perfect solution. So, it is still on your choice betweek "|-quote" or
:preserve.
By the way, it's much better to avoid word "|-quoted symbol". It is not a
proper name in Common Lisp. You can choose read character mode among
:upcase, :downcase, :preserve, and :inverse.

>  my final goal is to port your package to other CL platforms. In this
patch, I've done at least the following things:

Great!. several persons asked me of importing SWCLOS to non-ACL Common
Lisp, and some one actually tried.
Anyway, I might give you sugestions to make language depending part of
CLOS. The first booting part of SWCLOS using CLOS is very critical points,
Keep it up!

> This work is in scope of my exam project for "Artificial Intelligence:
Knowledge Representation" course in University of Bologna (Italy),

I very appriciate you to choose SWCLOS for you work.
If you do it, please up it to github as your own work.
And if you have any question of not only SWCLOS but much broader sense
Knowledge Representation.
You will be the main and best contributer of SWCLOS.

Thanks!
I will check your work later on soon.

PS.
I attach my paper and slide of my presentation on JIST this year.



2016-10-16 1:05 GMT+09:00 Chun Tian <notifications@github.com>:

**Comment by binghe** [comment]
Hi,

First of all, thank you for your detailed response! 

Sorry, "PURL" is indeed a typo, it's actuall "puri" [1], a portable version of Allegro's net.uri with exactly the same API.   There's another portable URI library in CL community, it's called "quri", however we cannot use it, because in this package "URI" is not a CLOS class but a structure.

I think I must have those |-quoted symbols literally in the source code, because in ANSI CL all standard symbols are upcases. If I change global readtable-case to "preserve", then there's no way for CL compiler to understand symbols like "defun" and "defmethod" or even "car" / "cdr".  However, I do need to set readtable to "preserve" when reading a RDF file. I used a "named-readtables" package to manage several separated readtables (with names!).

My latest work is in my fork of your Git repository [2], there're 132 commits after your point. Currently I've finished porting SWCLOS to Allegro CL 10.0 ANSI mode and LispWorks.   I depend on some other packages beside "puri", they're: named-readtables [3], closer-mop [4] and flexi-streams [5].  With help of these packages, now my version of SWCLOS is highly portable: all Allegro CL specific extensions to Common Lisp are not used any more.

I got some help from a MOP expert (Pascal Costanza, the author of Closer-MOP project), he helped me to understand and rewrite some private MOP methods in Allegro CL. For example, Allegro's excl::default-direct-superclasses generic function can be implemented in portable ways by (initialize-instance :around) and (reinitialize-instance :around) methods. excl::compute-effective-slot-definition-initargs is a little difficult, but fortunately PCL-based MOP implementations (CMUCL and SBCL) has this method too (so is CLISP and LispWorks).

But the work of porting to other open source CL platforms is blocked at RDFboot.cl (The first booting part of SWCLOS using CLOS). The main root cause is that, according to AMOP, "portable metaobject classes
cannot be redefined" (I've learnt this when I tried to submit a bug to SBCL, because SBCL crashed when loading SWCLOS), therefore your current way of redefining "rdfsClass" and many other classes is actually illegal and unportable. Currently I'm thinking very hard to work around of this issue by using lower level APIs from MOP.

I look forward for your further work to support RDF 1.1 and OWL 2.0 !!  I think you should focus at this high level (and just use your Allegro CL professional edition). Once you've done the work, I'll figure out how to make it portable to other CL platforms.  Your original work will be always a reference implementation for me.  Since this project is now connected to my votes in the exam and my future, I won't give up until I finished it.

Best Regards,

Chun Tian
University of Bologna

[1] http://www.cliki.net/puri
[2] https://github.com/binghe/SWCLOS
[3] http://www.cliki.net/named-readtables
[4] https://github.com/pcostanza/closer-mop
[5] http://weitz.de/flexi-streams/

**Comment by SeijiKoide** [comment]
Hi, Chun.

Please call me Seiji.

> there's no way for CL compiler to understand symbols like "defun" and
"defmethod" or even "car" / "cdr".

Yes, it is. However, in that case you cannot share symbols of XML datatypes
with lisp and XML.

It is one reason of mlisp for SWCLOS. You must ensure to read RDF/XML
format or ttl format entities into upcase symbol names.



> now my version of SWCLOS is highly portable: all Allegro CL specific
extensions to Common Lisp are not used any more.

Great and thanks!



> I got some help from a MOP expert (Pascal Costanza

Oh, Oh. You are lucky to catch him. I remember him very well on Lisp
workshop held at Genova.

I expect he also remember me. He is the best guy to ask helps on CLOS.

If any lisp workshop could be held at Bologna, I definitely be there. In
the case, I and you might do re-born the tutorial at Bologna.

You can contact key persons of
http://www.european-lisp-workshop.org/about.php and European Lisp Symposium
(ELS).

Woops! It is decided that ELS2017 held at Brussels.



> Currently I'm thinking very hard to work around of this issue by using
lower level APIs from MOP.

Well, firstly please tell me your idea BEFORE STARTING IT, because this
first step of porting may navigate you to a wrong path. I cannot imagine
how you can do it, even if I see your skill on coding of CL. On the other
hand, SBCL is a special one than other free CLs on the point that it is
easy to install and use it (except ACL) for novice. So, SBCL on Linux is
special in my mind. I will ask some information of SWCLOS porting to SBCL
to another colleague of porting SWCLOS.


Cheers

Seiji Koide



PS.

I found your home page and vitae. I am not sure it is good for your future
to tackle SWCLOS porting in your long life more than an exam. I don’t know
which way between academy and business you choose in your future. If you
really like and fascinated to lisp, it is no problem. You will get what you
want through Lisp Programming and enjoy your life in long time. However, if
you want economic success or to be popular in science in your life, SWCLOS
might be a problem, because the community of Lisp is not large right now.
And I must give you a notice that SWCLOS is unpopular yet in the community
of Semantic Webs. So, I very thank you to tackle porting SWCLOS. Anyway, I
can help you to join Franz, Inc. if you want. I can introduce you to the
CEO and recommend you to him. He once complained SWCLOS is difficult to
understand. He once tried to read the code of SWCLOS but gave up it. So, he
will welcome anyone who has skills and knowledge of Lisp, Semantic Webs,
and SWCLOS. You know I initially introduced Semantic Web to him and Franz.
Franz owes a lot to me. You know I ordered the development of AProlog, when
I belonged to a company.

2016-11-05 19:12 GMT+09:00 Chun Tian <notifications@github.com>:

**Comment by SeijiKoide** [comment]
I found my presentation file for SWCLOS tutorial that is held at
Internatonal Lisp Conference 2005.

2016-11-06 20:07 GMT+09:00 Seiji Koide <seijikoide0@gmail.com>:

**Pull request closed without merging**
